export const stackData = {
  frontend: [
    {
      id: 1,
      name: "HTML",
      icon: "html5",
      color: "#e34c26",
      background: "#f1e5e6",
    },
    {
      id: 2,
      name: "CSS",
      icon: "css3",
      color: "#2965f1",
      background: "#e8f0fe",
    },
    {
      id: 3,
      name: "Javascript",
      icon: "javascript",
      color: "#f7df1e",
      background: "#fffbe6",
    },
    {
      id: 4,
      name: "React",
      icon: "react",
      color: "#61dafb",
      background: "#e6fcff",
    },
    {
      id: 5,
      name: "React-Query",
      icon: "react-query",
      color: "#5cdb95",
      background: "#e6fffa",
    },
    {
      id: 6,
      name: "Redux",
      icon: "redux",
      color: "#764abc",
      background: "#f3e8fd",
    },
    {
      id: 7,
      name: "Sass",
      icon: "sass",
      color: "#c69",
      background: "#f9f2f4",
    },
    {
      id: 8,
      name: "Bootstrap",
      icon: "bootstrap",
      color: "#563d7c",
      background: "#f3e8fd",
    },
    {
      id: 9,
      name: "Material-ui",
      icon: "material-ui",
      color: "#0081cb",
      background: "#e6f4fe",
    },
    {
      id: 10,
      name: "Styled-Components",
      icon: "styled-components",
      color: "#db7093",
      background: "#ffeef0",
    },
    {
      id: 11,
      name: "Apollo GraphQL",
      icon: "apollo-graphql",
      color: "#311c87",
      background: "#f3e8fd",
    },
    {
      id: 13,
      name: "Flutter",
      icon: "flutter",
      color: "#02569b",
      background: "#e6f4fe",
    },
    {
      id: 14,
      name: "Angular",
      icon: "angular",
      color: "#dd0031",
      background: "#ffeef0",
    },
  ],
  backend: [
    {
      id: 1,
      name: "Node.js",
      icon: "node-dot-js",
      color: "#339933",
      background: "#e6ffe6",
    },
    {
      id: 2,
      name: "Express",
      icon: "express",
      color: "#000",
      background: "#fff",
    },
    {
      id: 3,
      name: "PostgreSQL",
      icon: "postgresql",
      color: "#336791",
      background: "#e6f4fe",
    },
    {
      id: 4,
      name: "Sequelize",
      icon: "sequelize",
      color: "#52b0e7",
      background: "#e6f4fe",
    },
    {
      id: 5,
      name: "MongoDB",
      icon: "mongodb",
      color: "#47a248",
      background: "#e6ffe6",
    },
    {
      id: 6,
      name: "Mongoose",
      icon: "mongoose",
      color: "#a9a9a9",
      background: "#f2f2f2",
    },
    {
      id: 7,
      name: "Redis",
      icon: "redis",
      color: "#3178c6",
      background: "#e6f4fe",
    },
    {
      id: 8,
      name: "REST API",
      icon: "rest-api",
      color: "#000",
      background: "#fff",
    },
  ],
  deployment: [
    {
      id: 1,
      name: "Git",
      icon: "git",
      color: "#f05032",
      background: "#ffe6e6",
    },
    {
      id: 2,
      name: "GitHub",
      icon: "github",
      color: "#181717",
      background: "#f2f2f2",
    },
    {
      id: 3,
      name: "Heroku",
      icon: "heroku",
      color: "#430098",
      background: "#f3e8fd",
    },
    {
      id: 4,
      name: "Vercel",
      icon: "vercel",
      color: "#000",
      background: "#fff",
    },
    {
      id: 5,
      name: "Travis CI",
      icon: "travis-ci",
      color: "#3eaaaf",
      background: "#e6f4fe",
    },
    {
      id: 6,
      name: "Circle CI",
      icon: "circleci",
      color: "#343434",
      background: "#f2f2f2",
    },
    {
      id: 7,
      name: "Netlify",
      icon: "netlify",
      color: "#00c7b7",
      background: "#e6fffa",
    },
    {
      id: 8,
      name: "Render",
      icon: "render",
      color: "#000",
      background: "#fff",
    },
  ],
  testing: [
    {
      id: 1,
      name: "Jest",
      icon: "jest",
      color: "#c21325",
      background: "#ffe6e6",
    },
    {
      id: 2,
      name: "React Testing Library",
      icon: "react-testing-library",
      color: "#e33332",
      background: "#ffe6e6",
    },
    {
      id: 3,
      name: "Mocha",
      icon: "mocha",
      color: "#8d6748",
      background: "#f9f2f4",
    },
    {
      id: 4,
      name: "Chai",
      icon: "chai",
      color: "#a30701",
      background: "#ffe6e6",
    },
    {
      id: 5,
      name: "Cypress",
      icon: "cypress",
      color: "#17202c",
      background: "#e6f4fe",
    },
    {
      id: 6,
      name: "Postman",
      icon: "postman",
      color: "#ff6c37",
      background: "#ffe6e6",
    },
  ],
  programmingLanguages: [
    {
      id: 1,
      name: "JavaScript",
      icon: "javascript",
      color: "#f7df1e",
      background: "#fffbe6",
    },
    {
      id: 2,
      name: "TypeScript",
      icon: "typescript",
      color: "#3178c6",
      background: "#e6f4fe",
    },
    {
      id: 3,
      name: "Python",
      icon: "python",
      color: "#3776ab",
      background: "#e6f4fe",
    },
    {
      id: 4,
      name: "Dart",
      icon: "dart",
      color: "#0175c2",
      background: "#e6f4fe",
    },
  ],
  others: [
    {
      id: 1,
      name: "Jira",
      icon: "jira",
      color: "#0052cc",
      background: "#e6f4fe",
    },
    {
      id: 2,
      name: "Pivotal Tracker",
      icon: "pivotal-tracker",
      color: "#ff6c37",
      background: "#ffe6e6",
    },
    {
      id: 3,
      name: "Trello",
      icon: "trello",
      color: "#0079bf",
      background: "#e6f4fe",
    },
  ],
};
